server.port: 19998
server.servlet.context-path: /elastic-learn

server.undertow.buffer-size: 10240
server.undertow.direct-buffers: true
server.undertow.threads.io: 32
server.undertow.threads.worker: 128

logging.level.com.winfred.spring.service: INFO
